[package]
authors = ["Machtan <jako3047@gmail.com>"]
name = "dero"
version = "0.3.0"

[[bin]]
doc = false
name = "dero"

[dependencies]
argonaut = "0.11.0"
hangeul2 = { path = "hangeul2" }
termion = "1"
